name: Build Operations Button Widget

# Controls when the workflow will run
on:    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: build      
        uses: actions/setup-node@v2
        with:
         node-version: 16.x        
      - run: npm ci
        working-directory: ./operations-button
      - run: npm run build-ci --if-present
      - name: Zip Frontend
        run: |
          cd operations-button/dist/apps/operations-button
          zip -r -q ../../../operations-button-plugin.zip *
      - name: Read @c8y/client version
        run: |
          export C8Y_VERSION=$(npm list @c8y/client | grep @c8y/client | awk -F@ '{print $2}' | tr -d '[:space:]')
          echo "::set-env name=C8Y_VERSION::$C8Y_VERSION"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          C8Y_VERSION: ${{ env.C8Y_VERSION }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }} for Cumulocity UI v${{ env.C8Y_VERSION }}        
          draft: false
          prerelease: false